security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                success_handler: redirect.after.login

            logout:       
                path: /logout
                target: /
                success_handler: redirect.after.logout
                invalidate_session: true

            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reserver$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contactsuccess$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reserversuccess$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reserverresult$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reserverinfo$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/accueilclient$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/voitures$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_USER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,     role: ROLE_SUPER_ADMIN }
        - { path: ^/,          role: ROLE_USER }