paiement_index:
    path:     /
    defaults: { _controller: "LocationBundle:Paiement:index" }
    methods:  GET

paiement_show:
    path:     /{id}/show
    defaults: { _controller: "LocationBundle:Paiement:show" }
    methods:  GET

paiement_new:
    path:     /new/{id}
    defaults: { _controller: "LocationBundle:Paiement:new" }
    methods:  [GET, POST]

paiement_new2:
    path:     /new2/{id}
    defaults: { _controller: "LocationBundle:Paiement:new2" }
    methods:  [GET, POST]

paiement_edit:
    path:     /{id}/edit
    defaults: { _controller: "LocationBundle:Paiement:edit" }
    methods:  [GET, POST]

paiement_edit1:
    path:     /{id}/edit1
    defaults: { _controller: "LocationBundle:Paiement:edit1" }
    methods:  [GET, POST]

paiement_edit2:
    path:     /{id}/edit2
    defaults: { _controller: "LocationBundle:Paiement:edit2" }
    methods:  [GET, POST]

paiement_delete:
    path:     /{id}/delete
    defaults: { _controller: "LocationBundle:Paiement:delete" }
    methods:  DELETE
