# app/config/routing.yml
scheduler_index:
    path:      /
    defaults:  { _controller: LocationBundle:Scheduler:index }
    methods:  [GET]

scheduler_create:
    path:      /appointment-create
    defaults:  { _controller: LocationBundle:Scheduler:create }
    methods:  [POST]

scheduler_update:
    path:      /appointment-update
    defaults:  { _controller: LocationBundle:Scheduler:update }
    methods:  [POST]

scheduler_delete:
    path:      /appointment-delete
    defaults:  { _controller: LocationBundle:Scheduler:delete }
    methods:  [DELETE]