typedepenses_index:
    path:     /
    defaults: { _controller: "LocationBundle:TypeDepenses:index" }
    methods:  GET

typedepenses_show:
    path:     /{id}/show
    defaults: { _controller: "LocationBundle:TypeDepenses:show" }
    methods:  GET

typedepenses_new:
    path:     /new
    defaults: { _controller: "LocationBundle:TypeDepenses:new" }
    methods:  [GET, POST]

typedepenses_edit:
    path:     /{id}/edit
    defaults: { _controller: "LocationBundle:TypeDepenses:edit" }
    methods:  [GET, POST]

typedepenses_delete:
    path:     /{id}/delete
    defaults: { _controller: "LocationBundle:TypeDepenses:delete" }
